# Generated by Django 5.2.10 on 2026-01-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='is_hidden',
        ),
    ]
