# Generated by Django 5.2.10 on 2026-01-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_communities_name_3031a9_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='community',
            name='communities_name_3031a9_idx',
        ),
    ]
