# Generated by Django 5.2.10 on 2026-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_remove_community_communities_name_3031a9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='division',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('year', 'branch', 'division')},
        ),
    ]
